x-common: &common
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
  restart: unless-stopped
  networks:
    - zpassfit-network

x-env: &env
  env_file: .env

services:
  zpassfit-ai:
    image: zpassfit-ai
    <<: [*common, *env]
    networks:
      - zpassfit-network

  zpassfit-backend:
    image: zpassfit-backend
    <<: [*common, *env]
    ports:
      - "8080:8080"

  zpassfit-postgres:
    image: postgres:alpine
    <<: [*common, *env]
    volumes:
      - zpassfit-postgres:/var/lib/postgresql

volumes:
  zpassfit-postgres:

networks:
  zpassfit-network: